"""M

Revision ID: 211dc2d046fe
Revises: ebf3d0039282
Create Date: 2024-10-27 20:12:34.066608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211dc2d046fe'
down_revision = 'ebf3d0039282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file', sa.String(length=255), nullable=False))
        batch_op.drop_column('resume')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('resume_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file_path', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('resume_file')

    # ### end Alembic commands ###
