"""empty message

Revision ID: 30baac6d681f
Revises: 0751becb2c1f
Create Date: 2022-12-04 23:09:00.997682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30baac6d681f'
down_revision = '0751becb2c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
