"""Updated user table

Revision ID: cf22d1ca3bbc
Revises: acb5786bbaec
Create Date: 2024-10-31 13:38:39.523974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf22d1ca3bbc'
down_revision = 'acb5786bbaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_file_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume_file_path')
        batch_op.drop_column('address')
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###
