"""Migrate

Revision ID: ebf3d0039282
Revises: ffd21491fbc8
Create Date: 2024-10-27 19:45:29.457033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf3d0039282'
down_revision = 'ffd21491fbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume_file_path')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('resume')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('resume_file_path')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file_path', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
