"""Update

Revision ID: fe1c772a14b3
Revises: 71e6e9d0cc42
Create Date: 2024-10-27 16:11:46.815063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1c772a14b3'
down_revision = '71e6e9d0cc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume_file_path')

    # ### end Alembic commands ###
