"""Initial migration.

Revision ID: ffd21491fbc8
Revises: fe1c772a14b3
Create Date: 2024-10-27 17:56:28.555532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd21491fbc8'
down_revision = 'fe1c772a14b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.String(length=255), nullable=False))
        batch_op.drop_column('resume_file')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('resume')

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
